### PR TITLE
Pass Int32 to db as integer

### LINKED ISSUE #122: Pass Int32 to_db as int
Change the Int32.to_db method to return an int directly and update specs as discussed in #120.

### PR DESCRIPTION
**Pull request by mikeeus**
Closes #122.

### CODE REVIEW

**Comment by mikeeus** [comment]
I just rebased this. Is it okay to merge or is it missing something?

**Comment by paulcsmith** [comment]
@mikeeus If you have a moment could you rebase this? If you're busy no problem. LMK and I'll branch and rebase it

**Comment by mikeeus** [comment]
Hey Paul, I reforked `lucky_record` and deleted my old fork because it was giving me issue before so I don't have access to the repository that I used to make this pull request (it says `unknown repository`). 

How can I get access to this branch again to rebase it?

**Comment by paulcsmith** [comment]
I would try installing https://github.com/github/hub and then do `hub checkout https://github.com/luckyframework/lucky_record/pull/124`. I *think* that should work!

**Comment by mikeeus** [comment]
Closing because I made a new pull request from my new fork.

**Pull request closed without merging**
